package stage_4.application.src;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stage_3.Employee;
import stage_3.Product;
import stage_3.Sale;
import stage_3.TeaShop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Teddy
 */
public class SalesFrame extends JFrame {

    /**
     * Creates new form SalesFrame
     */
    public SalesFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        salesTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        orderIdSalesTxt = new javax.swing.JTextField();
        itemNumberSalesTxt = new javax.swing.JTextField();
        totalSalesTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        productSalesTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        productIdSearchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        showSalesPanel = new javax.swing.JPanel();
        showSalejScrollPane = new javax.swing.JScrollPane();
        showSalesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Sales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 38, 138, -1));

        salesTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salesTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                salesTabbedPaneStateChanged(evt);
            }
        });

        jLabel2.setText("Order ID");

        jLabel3.setText("Product");

        jLabel5.setText("Total");

        jLabel6.setText("Number of Items");

        orderIdSalesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdSalesTxtActionPerformed(evt);
            }
        });

        totalSalesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalSalesTxtMouseClicked(evt);
            }
        });
        totalSalesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSalesTxtActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        productSalesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSalesTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemNumberSalesTxt)
                                    .addComponent(totalSalesTxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(114, 114, 114)
                                .addComponent(productSalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(112, 112, 112)
                                .addComponent(orderIdSalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(saveBtn)
                        .addGap(74, 74, 74)
                        .addComponent(resetBtn)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(orderIdSalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productSalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(itemNumberSalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalSalesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(saveBtn))
                .addGap(152, 152, 152))
        );

        salesTabbedPane.addTab("Add", jPanel1);

        jLabel7.setText("Order ID");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearBtn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(productIdSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(productIdSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(clearBtn)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        salesTabbedPane.addTab("Search", jPanel2);

        showSalesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        showSalesTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "orderId", "orderDate", "ProductId "
            }
        ));
        showSalejScrollPane.setViewportView(showSalesTable);

        javax.swing.GroupLayout showSalesPanelLayout = new javax.swing.GroupLayout(showSalesPanel);
        showSalesPanel.setLayout(showSalesPanelLayout);
        showSalesPanelLayout.setHorizontalGroup(
            showSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showSalesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showSalejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        showSalesPanelLayout.setVerticalGroup(
            showSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showSalesPanelLayout.createSequentialGroup()
                .addComponent(showSalejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        salesTabbedPane.addTab("Show Sales", showSalesPanel);

        getContentPane().add(salesTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 91, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderIdSalesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdSalesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIdSalesTxtActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        productIdSearchTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        orderIdSalesTxt.setText("");
        productSalesTxt.setText("");
        itemNumberSalesTxt.setText("");
        totalSalesTxt.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            // TODO add your handling code here
            String productId = productSalesTxt.getText();

            int productQuantity = Integer.parseInt(itemNumberSalesTxt.getText());

            Sale sale = new Sale();

            sale.setOrderDate(LocalDateTime.now());
            sale.setOrderId(orderIdSalesTxt.getText());

            TeaShop teaShop = new TeaShop();
            teaShop.setProducts(getProductFromFile("src/data/product.csv"));
            Product inventoryProduct = teaShop.getProduct(productId);

            if (inventoryProduct == null) {
                JOptionPane.showMessageDialog(this, "The Product Id does not exist");
            } else {
                Product product = new Product();
                product.setDistributor(inventoryProduct.getDistributor());
                product.setQuantity(productQuantity);
                product.setProductName(inventoryProduct.getProductName());
                product.setUnitPrice(inventoryProduct.getUnitPrice());
                product.setProductId(productId);
                inventoryProduct.setQuantity(inventoryProduct.getQuantity() - productQuantity);
                sale.addProduct(product);
                saveSales(sale, true);
                totalSalesTxt.setText(String.valueOf(sale.totalPrice()));
            }
        } catch (IOException ex) {
            Logger.getLogger(SalesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void productSalesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSalesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productSalesTxtActionPerformed

    private void totalSalesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSalesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSalesTxtActionPerformed

    private void totalSalesTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalSalesTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSalesTxtMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<Sale> sales = getSalesFromFile("src/data/sale.csv");
            Sale sale = findSalesDetails(sales, productIdSearchTxt.getText());
            if (sale != null) {
                JOptionPane.showMessageDialog(this, detailsOfSale(sale));
            } else {
                JOptionPane.showMessageDialog(this, detailsOfSale(sale));
            }
        } catch (IOException ex) {
            Logger.getLogger(SalesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void salesTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_salesTabbedPaneStateChanged
        // TODO add your handling code here:
        int selectTab = salesTabbedPane.getSelectedIndex();
        if (selectTab == 2) {
            addRowToJTable();

        }
    }//GEN-LAST:event_salesTabbedPaneStateChanged
     public void addRowToJTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) showSalesTable.getModel();
            ArrayList<Sale> list = getSalesFromFile("src/data/sale.csv");
            Object rowData[] = new Object[3];
            for (int i = 0; i < list.size(); i++) {
                //firstName,lastName,email,streetAddress,city,zipCode,state,telephone,sales_id,clientId
                rowData[0] = list.get(i).getOrderId();
                rowData[1] = list.get(i).getOrderDate();
                rowData[2] = list.get(i).getProducts().get(0).getProductId();
                model.addRow(rowData);
            }
            //((DefaultTableModel) clientReportTable.getModel()).setRowCount(0);
            this.showSalesTable.setModel(model);
            showSalejScrollPane.setViewportView(showSalesTable);
        } catch (IOException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private Sale findSalesDetails(ArrayList<Sale> sales, String order_id) {
        for (Sale sale : sales) {
            if (sale.getOrderId().equals(order_id)) {
                System.out.println("Find the sale");
                return sale;
            }
        }
        System.out.println("Did not find the sale");
        return null;
    }

    private ArrayList<Sale> getSalesFromFile(String srcdatasalecsv) throws FileNotFoundException, IOException {
        ArrayList<Sale> sales = new ArrayList<>();
        // File path is passed as parameter
        File file = new File(srcdatasalecsv);
        BufferedReader br = new BufferedReader(new FileReader(file));
        // Declaring a string variable
        String st;
        // Condition holds true till
        // there is character in a string
        br.readLine();
        while ((st = br.readLine()) != null) // Print the string
        {
            //firstName,lastName,email,streetAddress,city,zipCode,state,telephone,sales_id,clientId
            String data[] = st.split(",");
            Product product = new Product();
            product.setProductId(data[2]);
            ArrayList<Product> products = new ArrayList<>();
            products.add(product);
            System.out.println("ArraySize " + data.length);
            Sale sale = new Sale(data[0], LocalDateTime.parse(data[1]), products);
            sales.add(sale);
        }
        return sales;
    }

    private String detailsOfSale(Sale sale) {
        if (sale != null) {
            //orderId,orderDate,ProductId
            String result = "Here are detail of the sale : \n";
            result = result + "Order ID : " + sale.getOrderId() + "\n Order Date : " + sale.getOrderDate()
                    + "\n Product Id " + sale.getProducts().get(0).getProductId();
            return result;
        } else {
            return "The Sale does not exist";
        }
    }

    private void saveSales(Sale sale, boolean mode) {
        System.out.println("Saving new sale");
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("src/data/sale.csv", mode));
            if (mode == false) {
                writer.append("orderId,orderDate,ProductId");
            }
            writer.append("\n");
            writer.append(sale.getOrderId() + ",");
            writer.append(sale.getOrderDate() + ",");
            writer.append(sale.getProducts().get(0).getProductId());

            writer.close();

        } catch (IOException ex) {
            Logger.getLogger(SalesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private ArrayList<Product> getProductFromFile(String srcdataclientcsv) throws FileNotFoundException, IOException {
        ArrayList<Product> clients = new ArrayList<>();
        // File path is passed as parameter
        File file = new File(srcdataclientcsv);
        BufferedReader br = new BufferedReader(new FileReader(file));
        // Declaring a string variable
        String st;
        // Condition holds true till
        // there is character in a string
        br.readLine();
        while ((st = br.readLine()) != null) // Print the string
        {
            //firstName,lastName,email,streetAddress,city,zipCode,state,telephone,sales_id,clientId
            String data[] = st.split(",");
            System.out.println("ArraySize " + data.length);
            Product product = new Product(data[0], data[1], data[2], Double.parseDouble(data[3]), Integer.parseInt(data[4]), null);
            clients.add(product);
        }
        return clients;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField itemNumberSalesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField orderIdSalesTxt;
    private javax.swing.JTextField productIdSearchTxt;
    private javax.swing.JTextField productSalesTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTabbedPane salesTabbedPane;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JScrollPane showSalejScrollPane;
    private javax.swing.JPanel showSalesPanel;
    private javax.swing.JTable showSalesTable;
    private javax.swing.JTextField totalSalesTxt;
    // End of variables declaration//GEN-END:variables
}
